plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/annesiebenkees/Desktop/claude-workspace-vorlage/outputs/tet-dashboard/public"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]